<?php
$phases= [
 0=>[
     'phase'=>'Una comida bien preparada tiene sabores delicados que hay que retener en la boca para apreciarlos.',
     'author'=>'Tennessee Williams',
     'profession'=>'dramaturgo estadounidense'],
 1=>[
     'phase'=>'Un buen vino es como una buena película: dura un instante y te deja en la boca un sabor a gloria; es nuevo en cada sorbo y, como ocurre con las películas, nace y renace en cada saboreador.',
     'author'=>'Federico Fellini',
     'profession'=>'director de cine y guionista italiano'],
 2=>[
     'phase'=>' La cocina es un lenguaje mediante el cual se puede expresar armonía, creatividad, felicidad, belleza, poesía, complejidad, magia, humor, provocación y cultura.',
     'author'=>'Ferran Adrià',
     'profession'=>'cocinero español'],
 3=>[
     'phase'=>'La mejor red social es una mesa llena de buena comida y rodeada de personas que quieres.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 4=>[
     'phase'=>'Todo lo que necesitas es amor. Pero un poco de chocolate de vez en cuando no hace daño.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 5=>[
     'phase'=>'Aquí se come como en casa pero sin tener que lavar los platos.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 6=>[
     'phase'=>'Yo cocino con vino. A veces incluso lo agrego a la comida.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 7=>[
     'phase'=>'Nuestro horario: Abrimos cuando llegamos, cerramos cuando nos vamos, y si vienes y no estamos, es que no coincidimos.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 8=>[
     'phase'=>'¡Salvemos la Tierra! Es el único planeta con Cerveza.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 9=>[
     'phase'=>'Soy cocinero de esos que les corre aceite por las venas, que cocinan más con las tripas que con la cabeza y que se comen la vida a bocados de placer.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 10=>[
     'phase'=>'Barriga llena, corazón contento. ',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 11=>[
     'phase'=>'No dejes para mañana lo que puedas comer hoy.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 12=>[
     'phase'=>'El amor es tan importante como la comida, pero no alimenta.',
     'author'=>'Gabriel García Márquez',
     'profession'=>'director colombiano'],
 13=>[
     'phase'=>'Cocinamos con amor para que comas con conciencia.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 14=>[
     'phase'=>'Solo hay tres cosas que las mujeres necesitan en la vida: comida, agua y elogios.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 15=>[
     'phase'=>'En esta casa somos reales, decimos lo siento, comentemos errores, damos segundas oportunidades. Nos divertimos, abrazamos, perdonamos, amamos. Somos una familia.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 16=>[
     'phase'=>'Haré dos dietas porque con una me quedo con hambre.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 17=>[
     'phase'=>'Después de una buena cena, uno puede perdonar a cualquiera, incluso las propias relaciones.',
     'author'=>'Oscar Wilde',
     'profession'=>'dramaturgo británico'],
 18=>[
     'phase'=>'Sea usted bienvenido a nuestro restaurante y sobre todo bien bebido.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 19=>[
     'phase'=>'Mientras tengo comida en la boca, todas las preguntas importantes quedarán resueltas.',
     'author'=>'Franz Kafka',
     'profession'=>'escritor austrohúngaro'],
 20=>[
     'phase'=>'El secreto del éxito en la vida es comer lo que te gusta y dejar que la comida se pelee por dentro.',
     'author'=>'Mark Twain',
     'profession'=>'escritor estadounidense'],
 21=>[
     'phase'=>'No hay amor más sincero que el amor a la comida.',
     'author'=>'George Bernard Shaw',
     'profession'=>'dramaturgo irlandés'],
 22=>[
     'phase'=>'Haré dos dietas porque con una me quedo con hambre.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 23=>[
     'phase'=>'No busques el éxito. Busca la felicidad.',
     'author'=>'Ferran Adrià',
     'profession'=>'cocinero español'],
 24=>[
     'phase'=>'El chocolate te hace feliz. El café te hace persona.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 25=>[
     'phase'=>'A comer, beber y gozar. Que el mundo se va acabar.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 26=>[
     'phase'=>'Nuestra receta: 2kg de amor, 3kg de sinceridad, 4kg de paciencia, 2 litros de sonrisas, 1 puñado de besos y abrazos. Amasar bien y mezclar todo con cariño y respeto. Servir cada día.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 27=>[
     'phase'=>'La vida es como un restaurante. Nadie se va sin pagar.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 28=>[
     'phase'=>'En la tentación no se cae. Se entra por la puerta grande.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 29=>[
     'phase'=>'¡Felicidades! Ya puede comer todo lo que quiera. La operación bikini ha sido suspendida por causas metereológicas.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 30=>[
     'phase'=>'En este establecimiento se come y se bebe a cualquier hora pero se exige SONREIR!',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 31=>[
    'phase'=>'La vida es como un restaurante; Puedes tener lo que quieras siempre que estés dispuesto a pagar un precio por ello.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 32=>[
     'phase'=>'Nouvelle cuisine, traducido significa: no puedo creer que pagué 100€ y todavía tengo hambre.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 33=>[
     'phase'=>'Es más fácil ser fiel a un restaurante que a una mujer.',
     'author'=>'Federico Fellini',
     'profession'=>'director de cine y guionista italiano'],
 34=>[
     'phase'=>'No puede comprar la felicidad pero puede comprar una botella de vino que es lo mismo.',
     'author'=>'Anónimo',
     'profession'=>'Anónimo'],
 
];